### PR TITLE
Fix potential memory corruption in MQTTPUBLISH callback preparation

### LINKED ISSUE #16: Fix potential memory corruption
This resolves knolleary/pubsubclient#832. See also knolleary/pubsubclient#835, knolleary/pubsubclient#1045 and thingsboard/pubsubclient#9

---
The memmove command is executed without any sanity checking on used values causing random reboots when an MQTT package gets processed with an impossible topic length.
With a high rate test flow of MQTT messages this would sometimes corrupt memory after a few seconds.

### PR DESCRIPTION
**Pull request by hmueller01**
This is a rework to make handling the received message more transparent.

Resolves #16 by checking against the given `len` that is checked in `readPacket()` to fit in `this->buffer[]`.

### CODE REVIEW

**Comment by TD-er** [comment]
I've tried to compare your changes to what I did back then when this issue was reported: https://github.com/letscontrolit/ESPEasy/pull/3520/files

I didn't find anything wrong yet but still hard to compare as it is a different approach.

And maybe you can add some comment lines at the start showing what the structure is of a message.
I still find it hard to read.

Like this:
```
// MQTT Publish packet:
// See section 3.3 MQTT v3.1 protocol specification:
//  https://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/MQTT_V3.1_Protocol_Specific.pdf
// QoS0: No message ID
// QoS1 & 2:  Has Message ID
//
// - Header: 1 byte
// - remaining length: multibyte field
// - Topic length: 2 bytes  Starts at buffer[llen + 1]
// - Topic
// - Message ID: 2 bytes (only for QoS > 0)
// - Payload
```

File: src/PubSubClient.cpp [hunk 1]
```diff
@@ -338,16 +338,21 @@ void PubSubClient::handlePacket(uint8_t llen, size_t len) {
...
+                topic[topicLen] = '\0';               // end the topic as a 'C' string with \x00
+
                 if ((this->buffer[0] & 0x06) == MQTTQOS1) {
-                    uint16_t msgId = (this->buffer[llen + 3 + tl] << 8) + this->buffer[llen + 3 + tl + 1];
-                    payload = this->buffer + llen + 3 + tl + 2;
-                    callback(topic, payload, len - llen - 3 - tl - 2);
+                    // msgId (packet identifier) is only present for QOS > 0
+                    if (payloadLen < 2) return;  // payload must be >= 2, as we have the msgId before
+                    uint16_t msgId = (this->buffer[payloadOffset] << 8) + this->buffer[payloadOffset + 1];
+                    callback(topic, payload + 2, payloadLen - 2);
```
Comment (TD-er) [inline src/PubSubClient.cpp:355]: This is a bit confusing.
The `payloadOffset` is used here for parsing the `msgId` and the the callback is called with some `payload + 2`. (and ditto correction on `payloadLen`)

**Comment by hmueller01** [comment]
> Just a tip; When you add `Fixes: #16` in the start post, the issue will be closed automatically when you merge this.

Used the wrong key word :-(
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue
`Resolves` should work (anywhere in the description). W'll see.

**Comment by TD-er** [comment]
image

It now shows a linked PR, so it should be closed just fine when this gets merged

**Review by uschindler — APPROVED** [review]
This looks OK, but the commit is very unreadable.

It also differs from the fix for the same issue in the other thingsboard repository.

**Comment by TD-er** [comment]
> It also differs from the fix for the same issue in the other thingsboard repository.

Hmm that code in the linked Thingsboard repo looks like a 1-to-1 copy of my code.
At least using exactly the same variable names.

File: src/PubSubClient.cpp [hunk 2]
```diff
@@ -329,25 +329,48 @@ size_t PubSubClient::readPacket(uint8_t* lenLen) {
...
+                uint16_t topicLen = (this->buffer[hdrLen + 1] << 8) + this->buffer[hdrLen + 2];  // topic length in bytes
+                char* topic = (char*)(this->buffer + hdrLen + 3 - 1);  // set the topic in the LSB of the topic lenght, as we move it there
+                uint16_t payloadOffset = hdrLen + 3 + topicLen;        // payload starts after header and topic (if there is no packet identifier)
+                size_t payloadLen = length - payloadOffset;            // this might change by 2 if we have a QoS 1 or 2 message
+                uint8_t* payload = this->buffer + payloadOffset;
+
+                if (length < payloadOffset) {  // do not move outside the max bufferSize
+                    ERROR_PSC_PRINTF_P("handlePacket(): Suspicious topicLen (%u) points outside of received buffer length (%zu)\n", topicLen, length);
+                    return;
+                }
```
Comment (hmueller01) [inline src/PubSubClient.cpp:359]: Maybe it's better to stop the connection instead just return ...
```
                if (length < payloadOffset) {  // do not move outside the max bufferSize
                    _state = MQTT_DISCONNECTED;
                    _client->stop();
                    ERROR_PSC_PRINTF_P("handlePacket(): Suspicious topicLen (%u) points outside of received buffer length (%zu)\n", topicLen, length);
                    return;
```

Comment (TD-er) [reply src/PubSubClient.cpp:359]: Or you could let this function return a bool signalling success and act on the return value of this function call.

Comment (hmueller01) [reply src/PubSubClient.cpp:359]: Good idea, I'll do that. But still I am not sure if this is the correct reaction on wrong data in the message stream ...

The current implementation just crashes here (I haven't seen this, but it seems to happen). 
@uschindler What's your opinion on that?

Comment (hmueller01) [reply src/PubSubClient.cpp:360]: Ok, update is done. What do you think?

Comment (TD-er) [reply src/PubSubClient.cpp:360]: It is the same reaction to the broker as the broker will do when you send something unexpected.
For example start sending a publish message telling you will be sending N bytes.
If you send anything more you will be disconnected.
On sending less, you will be disconnected due to timeout or incorrect next header.

**Comment by hmueller01** [comment]
Is this good to merge? Or are are is there still something open / comments to make?

**Comment by TD-er** [comment]
I have not yet had time to look at it more closely on 'the big screen'.
But at first glance it seems OK.

**Comment by hmueller01** [comment]
Tested it in my environment for a few hours. Looks fine. So merging this.
